apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.namePrefix }}-psql-pv-claim
  labels:
    app: {{ .Values.namePrefix }}-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500M
