apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.namePrefix }}-psql-secrets
  namespace: {{ .Values.deploymentNamespace }}
  labels:
    app: {{ .Values.namePrefix }}-app
data:
  dbName: {{ template "dbNameEnc" . }}
  dbUser: {{ template "dbUserEnc" . }}
  dbPassword: {{ template "dbPasswordEnc" . }}
