apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.namePrefix }}-psql
  namespace: {{ .Values.deploymentNamespace }}
  labels:
    app: {{ .Values.namePrefix }}-app
spec:
  ports:
    - port: 5432
  selector:
    app: {{ .Values.namePrefix }}-app
    tier: psql
  clusterIP: None
