apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.namePrefix }}-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - {{ .Values.webHost }}
      secretName: {{ .Values.webHost }}-cert
  rules:
    - host: {{ .Values.webHost }}
      http:
        paths:
          - backend:
              serviceName: {{ .Values.namePrefix }}-webhost-service
              servicePort: http
