name: Production Deployment

on:
  release:
    types:
      - created


env:
  PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
  GKE_CLUSTER: cost-optimized-cluster-1    # Add your cluster name here.
  GKE_ZONE: us-central1-c   # Add your cluster zone here.
  DEPLOYMENT_NAME: hamzasite # Add your deployment name here.
  IMAGE: hamzasite
  SITE_PUBLIC_HOST: site.hrahimy.com

jobs:
  production-deploy:
    name: Deploy site to production
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCR_SERVICE_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      # Get the GKE credentials so we can deploy to the cluster
      - uses: google-github-actions/get-gke-credentials@v0.2.1
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ secrets.GCR_SERVICE_KEY }}

      - uses: WyriHaximus/github-action-helm3@v2
        name: Deploy
        with:
          exec: |-
            helm upgrade ${{ env.DEPLOYMENT_NAME }} ./charts/site/ \
            --install --wait --atomic \
            --namespace=hamzasite-production \
            --create-namespace \
            --set="namePrefix=$DEPLOYMENT_NAME" \
            --set="imageRefUri=gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA" \
            --set=deploymentNamespace=hamzasite-production \
            --set="webHost=$SITE_PUBLIC_HOST" \
            --set="sqlDb.name=$SQLDB_NAME" \
            --set="sqlDb.user=$SQLDB_USER" \
            --set="sqlDb.password=$SQLDB_PASSWORD" \
        env:
          SQLDB_NAME: ${{ secrets.SQLDB_NAME }}
          SQLDB_USER: ${{ secrets.SQLDB_USER }}
          SQLDB_PASSWORD: ${{ secrets.SQLDB_PASSWORD }}
